---
- hosts: dummy
  gather_facts: false

  tasks:
    - name: 1.1 Add epel repo
      become: true
      become_method: sudo
      yum: 
        name: epel-release
        state: latest     
    - name: 1.2 Install nginx Web server
      become: true
      become_method: sudo
      yum:
        name: nginx
        state: latest
    - name: 1.3 Start nginx
      become: true
      become_method: sudo
      service:
        name: nginx
        state: started

        